# =============================================================================
# 04_phylogeneticSignalAnalysis.R
#
# Tests for phylogenetic signal in two species-level niche position traits:
#   1. Temporal niche position: abundance-weighted mean week of capture,
#      representing where in the season a species is typically active.
#   2. Habitat niche position: abundance-weighted mean site-level plant beta
#      diversity (H_plant_bc), representing the typical habitat heterogeneity
#      context in which a species occurs.
#
# Motivation: The co-occurrence and turnover models (scripts 04-05) show that
# phylogenetic distance is a strong predictor across all analyses. Two
# mechanisms could drive this:
#   (a) Ecological conservatism: related species share similar phenological
#       or habitat niches due to shared ancestry, leading to greater overlap
#       and competition.
#   (b) Character displacement: competition between related species has driven
#       divergence in timing or habitat use.
# Under (a), both traits should show strong phylogenetic signal (K ≈ 1,
# λ ≈ 1). Under (b), signal should be weak or absent.
#
# Tests:
#   - Blomberg's K (randomisation, 999 permutations)
#   - Pagel's λ (likelihood ratio test vs. λ = 0)
#   - Mantel test: pairwise |Δtrait| ~ cophenetic distance
#   - Ancestral state reconstruction (contMap) for visualization
#
# NOTE on week numbers: week-of-year (1–52) is treated as linear. This is
# valid for most continental US carabids whose activity is concentrated in
# spring–fall (weeks 14–44). Species with bimodal spring/fall activity, or
# those active in weeks 1 and 52 (i.e., spanning the year boundary), will
# have inflated variance in this metric. Inspect contMap output for such cases.
#
# NOTE on habitat niche position: habitat_PC1 is the score of each site on the
# first PCoA axis of between-site Jaccard distances (plant communities pooled
# to site level). Species' habitat niche = abundance-weighted mean PC1 across
# capture sites. PC1 sign is arbitrary; inspect site_habitat_position.csv to
# determine which end of the axis corresponds to forested vs. open/xeric sites.
# This replaces the earlier H_plant_bc approach, which measured site-level
# habitat heterogeneity (a site property) rather than habitat position
# (a species-level niche trait).
#
# Prerequisites:
#   00_buildDiversityMetrics.R  → phylogeny and tax_lookup logic
#   01_buildHabitatHeterogeneity.R → data/derivedData/site_habitat_position.csv
#
# Outputs:
#   data/derivedData/species_niche_positions.csv
#   data/derivedData/phylogenetic_signal_results.csv
#   figures/contMap_temporal_niche.png
#   figures/contMap_habitat_niche.png
#   figures/mantel_temporal.png
#   figures/mantel_habitat.png
# =============================================================================

library(tidyverse)
library(ape)
library(phytools)
library(picante)
library(vegan)


# Minimum capture threshold for reliable niche position estimates
MIN_CAPTURES <- 20
MIN_SITES    <- 3

EXCLUDE_SITES <- c("LAJA", "GUAN", "PUUM")


# -----------------------------------------------------------------------------
# 1. Load carabid data
# -----------------------------------------------------------------------------

df <- read.csv("data/neon.df.csv") %>%
  mutate(
    collectDate = as.Date(collectDate),
    year        = lubridate::year(collectDate),
    week_num    = lubridate::week(collectDate)
  ) %>%
  filter(
    sampleType %in% c("carabid", "other carabid"),
    !siteID %in% EXCLUDE_SITES,
    taxonRank == "species"
  )


# -----------------------------------------------------------------------------
# 2. Load phylogeny and build taxon lookup (mirrors 00_buildDiversityMetrics.R)
# -----------------------------------------------------------------------------

tree_raw <- read.tree("data/phylogeny/roughTree.DNA.droppedseqs.newick")

tax_lookup <- df %>%
  select(taxonID, scientificName) %>%
  distinct() %>%
  mutate(
    genus_species = paste(
      stringr::word(scientificName, 1),
      stringr::word(scientificName, 2),
      sep = "_"
    )
  )

tree_taxa <- tibble(tip = tree_raw$tip.label) %>%
  mutate(genus_species = stringr::str_extract(tip, "^[^_]+_[^_]+"))

tax_lookup <- tax_lookup %>%
  inner_join(tree_taxa, by = "genus_species")

# Add tip labels to the beetle data
df <- df %>%
  left_join(select(tax_lookup, taxonID, tip), by = "taxonID")


# -----------------------------------------------------------------------------
# 3. Load site habitat position (PC1 from between-site plant PCoA)
# -----------------------------------------------------------------------------
# Generated by 01_buildHabitatHeterogeneity.R section 6.
# habitat_PC1 is the dominant axis of plant community compositional variation
# across NEON continental sites (pooled presence/absence per site, Jaccard).

site_hab_pos <- read.csv("data/derivedData/site_habitat_position.csv") %>%
  select(siteID, habitat_PC1)


# -----------------------------------------------------------------------------
# 4. Calculate species-level temporal niche position
# -----------------------------------------------------------------------------
# Abundance-weighted mean week of capture across all sites and years.

temporal_niche <- df %>%
  filter(!is.na(week_num), !is.na(individualCount), individualCount > 0) %>%
  group_by(taxonID, tip) %>%
  summarise(
    temporal_niche  = weighted.mean(week_num, individualCount, na.rm = TRUE),
    total_count     = sum(individualCount, na.rm = TRUE),
    n_sites_temp    = n_distinct(siteID),
    .groups         = "drop"
  )


# -----------------------------------------------------------------------------
# 5. Calculate species-level habitat niche position
# -----------------------------------------------------------------------------
# Abundance-weighted mean habitat_PC1 across sites where the species occurs.
# This places each species on the dominant axis of between-site habitat
# variation (PC1 from plant community PCoA), weighted by how many individuals
# were captured at each site. Species captured mostly at forested/mesic sites
# will have a different PC1 score than those captured at open/xeric sites.

habitat_niche <- df %>%
  group_by(taxonID, tip, siteID) %>%
  summarise(site_count = sum(individualCount, na.rm = TRUE), .groups = "drop") %>%
  left_join(site_hab_pos, by = "siteID") %>%
  filter(!is.na(habitat_PC1), site_count > 0) %>%
  group_by(taxonID, tip) %>%
  summarise(
    habitat_niche = weighted.mean(habitat_PC1, site_count, na.rm = TRUE),
    n_sites_hab   = n_distinct(siteID),
    .groups       = "drop"
  )


# -----------------------------------------------------------------------------
# 6. Combine, apply sample-size filter, and match to phylogeny
# -----------------------------------------------------------------------------

niche_df <- temporal_niche %>%
  full_join(habitat_niche, by = c("taxonID", "tip")) %>%
  filter(
    !is.na(tip),
    total_count  >= MIN_CAPTURES,
    n_sites_temp >= MIN_SITES,
    n_sites_hab  >= MIN_SITES
  )

message(sprintf("%d species pass sample size filters (>= %d captures, >= %d sites)",
                nrow(niche_df), MIN_CAPTURES, MIN_SITES))

# Prune tree to species that pass filters and have tip labels
tips_keep   <- niche_df$tip
tree_pruned <- drop.tip(tree_raw, setdiff(tree_raw$tip.label, tips_keep))
tree_rooted <- midpoint.root(tree_pruned)

# Align niche_df to pruned tree order
niche_df <- niche_df %>%
  filter(tip %in% tree_rooted$tip.label)

message(sprintf("%d species matched to pruned phylogeny", nrow(niche_df)))

# -----------------------------------------------------------------------------
# Branch-length sanity check
# -----------------------------------------------------------------------------
# phylosig(method = "K") inverts the phylogenetic covariance matrix C.
# Zero-length branches create linearly dependent rows/columns → singular C.
# This is common with rough/unresolved newick trees.
# Fix: replace zero-length edges with a negligible positive value (1e-7).
# This has no practical effect on the signal statistics but prevents the
# Lapack singularity error. A warning is issued so users know it happened.

n_zero_branches <- sum(tree_rooted$edge.length == 0, na.rm = TRUE)

if (n_zero_branches > 0) {
  warning(sprintf(
    paste0("%d zero-length branches detected in the pruned tree. ",
           "Replacing with 1e-7 to avoid singular covariance matrix in phylosig(). ",
           "Consider resolving polytomies in the source phylogeny for a cleaner fix."),
    n_zero_branches
  ))
  tree_rooted$edge.length[tree_rooted$edge.length == 0] <- 1e-7
}

message(sprintf("Branch lengths — min: %.6f, median: %.4f, max: %.4f",
                min(tree_rooted$edge.length),
                median(tree_rooted$edge.length),
                max(tree_rooted$edge.length)))

# Named vectors for phylogenetic signal tests
temporal_vec <- setNames(niche_df$temporal_niche, niche_df$tip)
habitat_vec  <- setNames(niche_df$habitat_niche,  niche_df$tip)

write.csv(niche_df, "data/derivedData/species_niche_positions.csv", row.names = FALSE)


# -----------------------------------------------------------------------------
# 7. Blomberg's K
# -----------------------------------------------------------------------------

message("\n--- Blomberg's K (999 permutations) ---")

k_temporal <- phylosig(tree_rooted, temporal_vec, method = "K",
                       test = TRUE, nsim = 999)
k_habitat  <- phylosig(tree_rooted, habitat_vec,  method = "K",
                       test = TRUE, nsim = 999)

message(sprintf("Temporal niche:  K = %.3f, p = %.4f", k_temporal$K, k_temporal$P))
message(sprintf("Habitat niche:   K = %.3f, p = %.4f", k_habitat$K,  k_habitat$P))


# -----------------------------------------------------------------------------
# 8. Pagel's lambda
# -----------------------------------------------------------------------------

message("\n--- Pagel's lambda (LRT vs. lambda = 0) ---")

lambda_temporal <- phylosig(tree_rooted, temporal_vec, method = "lambda", test = TRUE)
lambda_habitat  <- phylosig(tree_rooted, habitat_vec,  method = "lambda", test = TRUE)

message(sprintf("Temporal niche:  lambda = %.3f, p = %.4f",
                lambda_temporal$lambda, lambda_temporal$P))
message(sprintf("Habitat niche:   lambda = %.3f, p = %.4f",
                lambda_habitat$lambda,  lambda_habitat$P))


# -----------------------------------------------------------------------------
# 9. Save signal results
# -----------------------------------------------------------------------------

signal_results <- tibble(
  trait       = c("temporal_niche", "habitat_niche"),
  K           = c(k_temporal$K,          k_habitat$K),
  K_p         = c(k_temporal$P,          k_habitat$P),
  lambda      = c(lambda_temporal$lambda, lambda_habitat$lambda),
  lambda_p    = c(lambda_temporal$P,      lambda_habitat$P),
  n_species   = nrow(niche_df)
)

write.csv(signal_results, "data/derivedData/phylogenetic_signal_results.csv",
          row.names = FALSE)

print(signal_results)


# -----------------------------------------------------------------------------
# 10. Mantel test: pairwise trait distance ~ phylogenetic distance
# -----------------------------------------------------------------------------
# Tests whether closely related species have more similar niche positions.
# Complements K/lambda by capturing the pairwise relationship directly.

message("\n--- Mantel tests (999 permutations) ---")

# Cophenetic (patristic) distance matrix, subset to species in niche_df
coph_mat <- cophenetic(tree_rooted)
coph_mat <- coph_mat[niche_df$tip, niche_df$tip]

# Pairwise absolute trait differences
temp_dist <- as.matrix(dist(temporal_vec[niche_df$tip]))
hab_dist  <- as.matrix(dist(habitat_vec[niche_df$tip]))

mantel_temporal <- mantel(as.dist(temp_dist), as.dist(coph_mat),
                          method = "pearson", permutations = 999)
mantel_habitat  <- mantel(as.dist(hab_dist),  as.dist(coph_mat),
                          method = "pearson", permutations = 999)

message(sprintf("Temporal niche ~ phylo dist:  r = %.3f, p = %.4f",
                mantel_temporal$statistic, mantel_temporal$signif))
message(sprintf("Habitat niche  ~ phylo dist:  r = %.3f, p = %.4f",
                mantel_habitat$statistic,  mantel_habitat$signif))


# -----------------------------------------------------------------------------
# 11. Ancestral state reconstruction (contMap)
# -----------------------------------------------------------------------------
# ML ancestral state reconstruction mapped onto phylogeny. Saved as PNG.

# Temporal niche
png("figures/contMap_temporal_niche.png", width = 800, height = 1200, res = 120)
contMap(tree_rooted, temporal_vec, plot = FALSE) %>%
  { .$cols <- colorRampPalette(c("#2C7BB6", "#ABD9E9", "#FFFFBF", "#FDAE61", "#D7191C"))(1000); . } %>%
  plot(lwd = 2, fsize = 0.35, leg.txt = "Mean week of capture",
       title = "Temporal Niche Position")
dev.off()

# Habitat niche
png("figures/contMap_habitat_niche.png", width = 800, height = 1200, res = 120)
contMap(tree_rooted, habitat_vec, plot = FALSE) %>%
  { .$cols <- colorRampPalette(c("#2C7BB6", "#ABD9E9", "#FFFFBF", "#FDAE61", "#D7191C"))(1000); . } %>%
  plot(lwd = 2, fsize = 0.35, leg.txt = "Mean habitat PC1",
       title = "Habitat Niche Position (plant community PCoA axis 1)")
dev.off()


# -----------------------------------------------------------------------------
# 12. Mantel scatter plots
# -----------------------------------------------------------------------------

plot_mantel <- function(trait_dist, coph_mat, trait_label, filename,
                        mantel_r, mantel_p) {
  df_plot <- tibble(
    phylo_dist = as.vector(as.dist(coph_mat)),
    trait_diff = as.vector(as.dist(trait_dist))
  )
  
  label <- sprintf("Mantel r = %.3f, p = %.4f", mantel_r, mantel_p)
  
  ggplot(df_plot, aes(x = phylo_dist, y = trait_diff)) +
    geom_point(alpha = 0.15, size = 0.8, color = "grey40") +
    geom_smooth(method = "lm", color = "#2E86AB", se = TRUE) +
    annotate("text", x = Inf, y = Inf, label = label,
             hjust = 1.1, vjust = 1.5, size = 3.5) +
    theme_classic() +
    labs(
      x = "Cophenetic distance",
      y = paste0("|Δ ", trait_label, "|"),
      title = paste0("Pairwise trait similarity vs. phylogenetic distance\n",
                     trait_label)
    )
}

plot_mantel(temp_dist, coph_mat, "Temporal niche position",
            "figures/mantel_temporal.png",
            mantel_temporal$statistic, mantel_temporal$signif)
ggsave("figures/mantel_temporal.png", width = 5, height = 4)

plot_mantel(hab_dist, coph_mat, "Habitat niche position",
            "figures/mantel_habitat.png",
            mantel_habitat$statistic, mantel_habitat$signif)
ggsave("figures/mantel_habitat.png", width = 5, height = 4)

message("\nDone. Results written to data/derivedData/ and figures/")